### ISSUE TITLE
Terminology Clean-up

### ISSUE THREAD

**Issue by MccartyADI** [analogdevicesinc/aditof-sdk-rework#105]
Remote the term "Afe" from any APIs, replace with "camera" or "sensor" as appropriate.

**Comment by dNechita** [comment]
This has been implemented, right? @btogorean @SeptimiuVana

**Comment by SeptimiuVana** [comment]
Yes, at this commit https://github.com/analogdevicesinc/aditof-sdk-rework/commit/e1fbcfd79477722f2e61a2f3edd5c431647617a5
