### ISSUE TITLE
why rework, what's the major difference, when will it be available?

### ISSUE THREAD

**Issue by funshine** [analogdevicesinc/aditof-sdk-rework#154]
Just curious

**Comment by dNechita** [comment]
The major difference is that it will support a different type of depth camera. "rework" is just a temporary name, we will rename to something more suggestive. I don't know when it will be available, sorry!

**Comment by funshine** [comment]
Great! that means sdk framework/api/stack [SDK stack](https://github.com/analogdevicesinc/aditof_sdk/blob/master/sdk/readme.md) would not changes a lot right?

**Comment by dNechita** [comment]
That is correct. There will be very few changes.
