### ISSUE TITLE
GUI AB display is not clipping saturated values

### ISSUE THREAD

**Issue by MccartyADI** [analogdevicesinc/aditof-sdk-rework#168]
![image](https://user-images.githubusercontent.com/32206907/127753446-c76b6cb0-c6ed-4d16-b185-e46ad23ce207.png)

**Comment by MccartyADI** [comment]
I can merge the fix for this but do not have privileges not enabled to assign an issue to myself

**Comment by dNechita** [comment]
I have sent you an invite.
