### ISSUE TITLE
Build without SSL 

### ISSUE THREAD

**Issue by MccartyADI** [analogdevicesinc/aditof-sdk-rework#170]
libwebsockets can be built without SSL requirement and should be for this project.   Please build and update readme with "-DLWS_WITH_SSL=OFF" option for libwebsockets.

Requiring SSL install is problematic for creating a generically redistributable package and introduces export compliance challenges and we frankly just don't need it by default.

**Comment by dNechita** [comment]
We will turn it off. Initially, we didn't think of setting this to OFF and instead we fixed the problem by adding the SSL binaries. So we didn't have a reason to enable the SSL.
