### ISSUE TITLE
Refactor usage of FrameDataType and modes

### ISSUE THREAD

**Issue by VLitanADI** [analogdevicesinc/aditof-sdk-rework#45]
Create appropriate`DepthSensorFrameType` for ITOF camera and properly allocate frame memory depending on selected frame type. Each `DepthSensorFrameType` shall corespond to a camera mode with the same name / type.

- [x]  populate `vector<DepthSensorFrameType>` with the appropriate values according to this table 
 ![image](https://user-images.githubusercontent.com/70146671/116046593-e5b58980-a67b-11eb-93d2-90b54ef13941.png)
- [x] The method `setFrameType` from the depthSensor class shall also set the mode of the camera coresponding to the desired frame type
- [x] - Implement this change on target: only write a register 
- [x] - Implement on network:  no changes 

- [x]  refactor `allocFrameData` in order to allocate only what is necessary (described in current Frame type)

**Comment by VLitanADI** [comment]
Possible types of `FrameDataDetails`  /  `DepthSensorFrameContent` (for itof):

- header
- raw
- depth
- ir
- xyz

**Comment by dNechita** [comment]
Thanks John. Will keep this in mind.
